---
name: unit test (backend)
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: nest_todo_test
          MYSQL_ROOT_PASSWORD: passwd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run backend tests
        run: |
          yarn lint
          yarn test
          yarn test:e2e
